import type { GalleryMediaItem, GalleryVideo } from "@/types/gallery";

/** Central destinations for school-approved media when it is supplied. */
export const galleryMediaPaths = {
  campus: (fileName: string) => `/images/gallery/campus/${fileName}`,
  classroom: (fileName: string) => `/images/gallery/classroom/${fileName}`,
  sports: (fileName: string) => `/images/gallery/sports/${fileName}`,
  activities: (fileName: string) => `/images/gallery/activities/${fileName}`,
  events: (fileName: string) => `/images/gallery/events/${fileName}`,
  achievements: (fileName: string) => `/images/gallery/achievements/${fileName}`,
  videos: (fileName: string) => `/videos/${fileName}`,
} as const;

/**
 * Intentional development placeholders only. These do not represent, depict, or
 * claim to document Veena Vadini Public School. Set isPlaceholder to false only
 * when verified, approved school media has been placed at the referenced path.
 */
export const gallerySeed: readonly GalleryMediaItem[] = [
  {
    id: "gallery-campus-01",
    slug: "sample-campus-perspective",
    title: "Campus Perspective",
    caption: "Sample gallery placeholder — replace with an approved campus photograph.",
    alt: "Branded placeholder reserved for an approved Veena Vadini campus photograph.",
    category: "Campus",
    mediaType: "image",
    src: galleryMediaPaths.campus("campus-01.webp"),
    thumbnailSrc: galleryMediaPaths.campus("campus-01-thumb.webp"),
    width: 1800,
    height: 1200,
    featured: true,
    order: 1,
    captureDate: null,
    visibility: "public",
    status: "published",
    layout: "dominant",
    isPlaceholder: true,
  },
  {
    id: "gallery-classroom-01",
    slug: "sample-classroom-moment",
    title: "Classroom Moment",
    caption: "Sample gallery placeholder — replace with approved classroom media.",
    alt: "Branded placeholder reserved for an approved classroom photograph.",
    category: "Classroom",
    mediaType: "image",
    src: galleryMediaPaths.classroom("classroom-01.webp"),
    thumbnailSrc: galleryMediaPaths.classroom("classroom-01-thumb.webp"),
    width: 1200,
    height: 1500,
    featured: true,
    order: 2,
    captureDate: null,
    visibility: "public",
    status: "published",
    layout: "portrait",
    isPlaceholder: true,
  },
  {
    id: "gallery-activities-01",
    slug: "sample-creative-activity",
    title: "Creative Activity",
    caption: "Sample gallery placeholder — replace with approved activity media.",
    alt: "Branded placeholder reserved for an approved school activity photograph.",
    category: "Activities",
    mediaType: "image",
    src: galleryMediaPaths.activities("activity-01.webp"),
    thumbnailSrc: galleryMediaPaths.activities("activity-01-thumb.webp"),
    width: 1500,
    height: 1100,
    featured: true,
    order: 3,
    captureDate: null,
    visibility: "public",
    status: "published",
    layout: "landscape",
    isPlaceholder: true,
  },
  {
    id: "gallery-sports-01",
    slug: "sample-sports-moment",
    title: "Sports Moment",
    caption: "Sample gallery placeholder — replace with approved sports media.",
    alt: "Branded placeholder reserved for an approved school sports photograph.",
    category: "Sports",
    mediaType: "image",
    src: galleryMediaPaths.sports("sports-01.webp"),
    thumbnailSrc: galleryMediaPaths.sports("sports-01-thumb.webp"),
    width: 1200,
    height: 1200,
    featured: true,
    order: 4,
    captureDate: null,
    visibility: "public",
    status: "published",
    layout: "square",
    isPlaceholder: true,
  },
  {
    id: "gallery-cultural-01",
    slug: "sample-cultural-moment",
    title: "Cultural Moment",
    caption: "Sample gallery placeholder — replace with approved cultural-event media.",
    alt: "Branded placeholder reserved for an approved cultural event photograph.",
    category: "Cultural Events",
    mediaType: "image",
    src: galleryMediaPaths.events("cultural-01.webp"),
    thumbnailSrc: galleryMediaPaths.events("cultural-01-thumb.webp"),
    width: 1800,
    height: 1000,
    featured: true,
    order: 5,
    captureDate: null,
    visibility: "public",
    status: "published",
    layout: "wide",
    isPlaceholder: true,
  },
  {
    id: "gallery-celebration-01",
    slug: "sample-celebration-moment",
    title: "Celebration Moment",
    caption: "Sample gallery placeholder — replace with approved celebration media.",
    alt: "Branded placeholder reserved for an approved school celebration photograph.",
    category: "Celebrations",
    mediaType: "image",
    src: galleryMediaPaths.events("celebration-01.webp"),
    thumbnailSrc: galleryMediaPaths.events("celebration-01-thumb.webp"),
    width: 1200,
    height: 1500,
    featured: false,
    order: 6,
    captureDate: null,
    visibility: "public",
    status: "published",
    layout: "portrait",
    isPlaceholder: true,
  },
  {
    id: "gallery-students-01",
    slug: "sample-school-life-moment",
    title: "School-Life Moment",
    caption: "Sample gallery placeholder — replace with approved school-life media.",
    alt: "Branded placeholder reserved for an approved school-life photograph.",
    category: "Students",
    mediaType: "image",
    src: galleryMediaPaths.activities("school-life-01.webp"),
    thumbnailSrc: galleryMediaPaths.activities("school-life-01-thumb.webp"),
    width: 1500,
    height: 1100,
    featured: false,
    order: 7,
    captureDate: null,
    visibility: "public",
    status: "published",
    layout: "landscape",
    isPlaceholder: true,
  },
] as const;

/** No URLs are assigned until the school approves actual hosted or local videos. */
export const videoSeed: readonly GalleryVideo[] = [
  {
    id: "video-school-life-01",
    slug: "sample-school-life-film",
    title: "School-Life Film",
    caption: "Sample video placeholder — an approved school-life film can be added here later.",
    alt: "Branded placeholder for a future approved school-life video.",
    thumbnail: galleryMediaPaths.events("video-school-life-poster.webp"),
    videoUrl: null,
    provider: "local",
    duration: null,
    category: "Activities",
    visibility: "public",
    status: "published",
    order: 1,
    featured: true,
    isPlaceholder: true,
  },
  {
    id: "video-campus-01",
    slug: "sample-campus-tour",
    title: "Campus Tour",
    caption: "Sample video placeholder — an approved campus tour can be added here later.",
    alt: "Branded placeholder for a future approved campus-tour video.",
    thumbnail: galleryMediaPaths.campus("video-campus-tour-poster.webp"),
    videoUrl: null,
    provider: "local",
    duration: null,
    category: "Campus",
    visibility: "public",
    status: "published",
    order: 2,
    featured: false,
    isPlaceholder: true,
  },
] as const;
