import type { Notice } from "@/types/content";

/**
 * Temporary local records only. These are deliberately labelled as demo
 * content and must be replaced with verified school announcements before use.
 */
export const noticeSeed: readonly Notice[] = [
  {
    id: "demo-notice-admissions",
    slug: "demo-admission-notice",
    title: "Demo Admission Notice",
    summary: "Placeholder content showing how a school admission update will appear once verified information is available.",
    description: "This is sample notice content for the website interface only. It is not an official admission announcement from Veena Vadini Public School.\n\nReplace this text with verified school information, including any applicable dates, eligibility details, and contact instructions, before publishing a real notice.",
    publishDate: "2026-09-01",
    category: "Admissions",
    attachmentUrl: null,
    attachmentLabel: null,
    isImportant: true,
    isNew: true,
    visibility: "public",
    status: "published",
    createdAt: "2026-09-01T09:00:00.000Z",
    updatedAt: "2026-09-01T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "sample-notice-academic",
    slug: "sample-academic-notice",
    title: "Sample Academic Notice",
    summary: "A temporary example of the academic updates parents and students will be able to find here.",
    description: "This sample is included to demonstrate the notice-board experience. It does not communicate an official academic update.\n\nVerified school information can replace this content through the future content management connection without changing the public page layout.",
    publishDate: "2026-08-24",
    category: "Academic",
    attachmentUrl: null,
    attachmentLabel: null,
    isImportant: false,
    isNew: false,
    visibility: "public",
    status: "published",
    createdAt: "2026-08-24T09:00:00.000Z",
    updatedAt: "2026-08-24T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "demo-notice-examination",
    slug: "demo-examination-notice",
    title: "Demo Examination Notice",
    summary: "A placeholder for future examination-related communication after the school confirms the details.",
    description: "This is demonstration content only and should not be treated as an examination schedule, syllabus update, or official instruction.\n\nThe future notice workflow can add verified attachments when the school provides approved files.",
    publishDate: "2026-08-16",
    category: "Examination",
    attachmentUrl: null,
    attachmentLabel: null,
    isImportant: false,
    isNew: false,
    visibility: "public",
    status: "published",
    createdAt: "2026-08-16T09:00:00.000Z",
    updatedAt: "2026-08-16T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "sample-notice-holiday",
    slug: "sample-holiday-notice",
    title: "Sample Holiday Notice",
    summary: "A placeholder for a verified school holiday update and any accompanying clarification.",
    description: "This notice is sample content used only to show the future holiday-notice layout. It does not confirm a school holiday or closure.\n\nReplace it with approved school communication before publishing to parents and students.",
    publishDate: "2026-08-08",
    category: "Holiday",
    attachmentUrl: null,
    attachmentLabel: null,
    isImportant: false,
    isNew: false,
    visibility: "public",
    status: "published",
    createdAt: "2026-08-08T09:00:00.000Z",
    updatedAt: "2026-08-08T09:00:00.000Z",
    isDemo: true,
  },
] as const;
