import type { SchoolEvent } from "@/types/content";

/**
 * Temporary local records only. Dates, locations, and times are sample values
 * for the interface and must be replaced with verified school event details.
 */
export const eventSeed: readonly SchoolEvent[] = [
  {
    id: "sample-event-cultural",
    slug: "sample-cultural-event",
    title: "Sample Cultural Event",
    summary: "Placeholder event content showing the featured school-activity presentation.",
    description: "This is a sample event used to demonstrate the events experience. It is not a confirmed cultural programme or official school invitation.\n\nThe date, timing, venue, description, and approved media will be updated when the school provides verified event details.",
    date: "2026-09-05",
    startTime: "10:00",
    endTime: "12:00",
    category: "Cultural",
    location: "Sample venue — confirmation required",
    image: null,
    isFeatured: true,
    visibility: "public",
    status: "published",
    createdAt: "2026-08-28T09:00:00.000Z",
    updatedAt: "2026-08-28T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "demo-event-sports",
    slug: "demo-sports-activity",
    title: "Demo Sports Activity",
    summary: "A temporary entry for how a future school sports activity can be presented.",
    description: "This event is demo content only. It does not announce a confirmed sports activity, participant list, or school schedule.\n\nVerified details will replace this temporary content before any real event is shared publicly.",
    date: "2026-09-22",
    startTime: null,
    endTime: null,
    category: "Sports",
    location: "Sample location — confirmation required",
    image: null,
    isFeatured: false,
    visibility: "public",
    status: "published",
    createdAt: "2026-08-28T09:00:00.000Z",
    updatedAt: "2026-08-28T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "sample-event-meeting",
    slug: "sample-parent-meeting",
    title: "Sample Parent Meeting",
    summary: "A placeholder for a future parent conversation or school meeting update.",
    description: "This is a sample event record for the website layout. It is not an official parent-meeting announcement.\n\nThe school can later provide the approved purpose, timing, location, and any instructions for publication here.",
    date: "2026-10-10",
    startTime: "11:00",
    endTime: "12:00",
    category: "Meeting",
    location: "Sample location — confirmation required",
    image: null,
    isFeatured: false,
    visibility: "public",
    status: "published",
    createdAt: "2026-08-28T09:00:00.000Z",
    updatedAt: "2026-08-28T09:00:00.000Z",
    isDemo: true,
  },
] as const;
